// Generated by CoffeeScript 1.7.1
var folder, fs, path;

path = require('path');

fs = require('fs');

folder = path.resolve('apis');

exports.start = function(app) {
  var api, files, _i, _len, _results;
  files = fs.readdirSync(folder);
  _results = [];
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    api = files[_i];
    if (path.extname(api) === '.js') {
      _results.push((require(path.join(folder, api))).bind(app));
    }
  }
  return _results;
};
