// Generated by CoffeeScript 1.7.1
var hello;

hello = require('../addons/build/Release/hello');

exports.bind = function(app) {
  return app.get('/api/hello', function(req, res) {
    var output;
    output = hello.hello();
    return res.send(200, output);
  });
};
