// Generated by CoffeeScript 1.7.1
var logger, recognizer;

recognizer = require('../addons/build/Release/recognizer');

logger = {
  log: function(msg) {
    return console.log(msg);
  }
};

recognizer.initialize(logger);

exports.bind = function(app) {
  return app.get('/api/recognize/recognize', function(req, res) {
    var result;
    result = recognizer.recognize('pan', req.body);
    return res.send(200, result);
  });
};
