#ifndef CMDCODE_H_
#define CMDCODE_H_

#define CASCMD_HUP -1

#define CASCMD_NONE 0
#define CASCMD_EXPR 1
#define CASCMD_EVAL 2
#define CASCMD_EVALNUM 3
#define CASCMD_SIMPLIFY 4
#define CASCMD_EXPAND 5
#define CASCMD_SOLVE 6
#define CASCMD_SOLVESYSTEM 12
#define CASCMD_SOLVEODE 13
#define CASCMD_SOLVEIVP 14
#define CASCMD_FACTOR 7
#define CASCMD_DETERMINANT 8
#define CASCMD_INVERSE 9
#define CASCMD_RANK 10
#define CASCMD_NULLSPACE 11

#define CASREP_OK 0
#define CASREP_EXPR 1
#define CASREP_NONE 2
#define CASREP_HUP 100
#define CASREP_MSGERR 101
#define CASREP_SYSERR 102
#define CASREP_TOOLARGE 103
#define CASREP_INVALIDCMD 104
#define CASREP_BADEXPR 105
#define CASREP_CONVERR 106
#define CASREP_EMPTYMSG 107

#endif
